### ISSUE TITLE
Stuck on step

### ISSUE THREAD

**Issue by tyluRp** [hvalev/shiny-server-arm-docker#1]
I can't seem to get passed this step.
```bash
Step 29/57 : RUN ../bin/node ../ext/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure
 ---> Running in 0c6ee486a97e
../bin/node: 4: exec: ../bin/../ext/node/bin/node: not found
```

I originally tried building myself following that post on rstudio community, but got stuck here. I was hoping I could dodge it with docker but it seems I can't. Any ideas?

**Comment by tyluRp** [comment]
I actually just googled the error, should have prior to this issue. Seems its a pretty common thing to run into with ARM https://github.com/rstudio/shiny-server/issues/347

**Comment by hvalev** [comment]
No worries. Good luck with building the project! Thank you for your comment pointing at the solution.

**Comment by tyluRp** [comment]
Thanks! I have been trying without any luck. I just checked the build for this repo, which seemed to pass like 20ish days ago, so I can only assume the issue is something on my end.

**Comment by hvalev** [comment]
Are you building it in a docker container or directly on your system?

**Comment by tyluRp** [comment]
I am building it in a docker container on a raspberry pi. I finally got things resolved. I was doing two things wrong:

* Assumed that I needed to copy the `binding.gyp` file from `shiny-server` repo, but instead needed to copy from your repo.
* Failed the checksum when installing node because I was pulling from an outdated node version.

Thanks again for the support/this repository. It's been really helpful!

**Comment by hvalev** [comment]
No problem, glad you resolved the problem and documented your solution. It will certainly be helpful to others too! As far as I remember, the binding.gyp file is a workaround for an issue I was stuck at for ARM. The current node major version that shiny-server uses I believe is 12.x. Unfortunately, you need to use the version that shiny-server install script requires. If you'd like to test whether you can use a newer node version (the newest one right now I believe is 15.x) then take a look at the following two lines.

```
RUN sed -i '8s/.*/NODE_SHA256=abef7d431d6d0e067fe5797d4fe44039a5577f01ed9e40d7a3496cbb22502f55/' shiny-server/external/node/install-node.sh
RUN sed -i 's/linux-x64.tar.xz/linux-armv7l.tar.xz/' /shiny-server/external/node/install-node.sh
```
Here I basically switch the hashsum and node-image from the amd to arm, so that the correct arm-compatible image is used and the hashsum check passes. Good luck and let me know how it goes!

**Comment by tyluRp** [comment]
Good to know, thanks for the details. I have started to collect everything in a separate repo (basically a fork of yours) here: https://github.com/tyluRp/rstudio-shiny-server/blob/master/Dockerfile
