### ISSUE TITLE
Running apps without volume linking

### ISSUE THREAD

**Issue by shera-spare** [hvalev/shiny-server-arm-docker#24]
Hi there, 

thanks for the awesome project!
Is it possible to just put my app right inside the container via the dockerfile?

I tried it like this:
```
COPY shiny-server.conf /etc/shiny-server/shiny-server.conf

RUN mkdir /srv/shiny-server/app01
COPY app01/* /srv/shiny-server/app01/ 
RUN chmod -R 777 /srv/shiny-server/app01
```

But it doesnt work unfortunately, the website displays the following error message:
```
An error has occurred
The application failed to start.

Connection attempt was aborted.
```

When trying this, i left out the -v commands in docker run.

Any ideas/hints/links on how to fix this issue?

**Comment by hvalev** [comment]
You could and it should work as well. The only thing that comes to mind is that each app uses its own config file. Did you bake one in the image for your app as well? You can use the [hello app config file](https://github.com/hvalev/shiny-server-arm-docker/blob/master/hello/.shiny_app.conf) as reference. Let me know if this solves it.

**Comment by shera-spare** [comment]
Yes, the app01 folder contains ui.R, server.R and .shiny-app.conf. The shiny-app.conf is based on your hello app example:

```
# Instruct Shiny Server to run applications as the user "shiny"
run_as shiny;
preserve_logs true;
#allow_app_override true;
# Define a server that listens on port 3838
server {
  listen 3838;
  #hello world
  location /app01 {
    app_dir /srv/shiny-server/app01;
    log_dir /var/log/shiny-server/app01;
    log_file_mode 0777;
    app_init_timeout 1800;
    app_idle_timeout 1800;
  }
}
```

**Comment by hvalev** [comment]
Does it work when it's mounted from the host?

**Comment by shera-spare** [comment]
Yes, when i setup the structure you suggest, place the same app in ~/shiny-server/apps/app01 and run all 3 volumes in the docker run, it works.

**Comment by hvalev** [comment]
Okay, I have a couple of ideas. First you need to check the log of your shiny-server and see exactly what goes wrong. You can log into your container with docker exec -it shiny-server-arm /bin/sh or /bin/bash and go to the log folder. Also I took the liberty of going into your profile and checking out your [dockerfile](https://github.com/shera-spare/SeePi/blob/main/shiny_test/Dockerfile). I see that you have changed quite a few things, including changing the builder and production images, which can be a source of error (perhaps different pathing or packages not being linked properly). However, more importantly, it drew my attention that you're installing R libraries in the builder image and not in the production one, which may lead to the wrong user being assigned as the owner ([see here](https://stackoverflow.com/questions/41922113/shiny-server-error-on-webpage-an-error-has-occurred-the-application-failed-to-s)). This you can check easily using the hello world app, because if that is the case, the hello-world app won't work either. Finally, if none of those things yield anything (e.g. logs turn up not verbose enough and the idea about installing the R libraries in the production image), I would suggest staying as close to the dockerfile in this repository as possible and slowly make incremental changes in yours making sure that everything works in each successive step.
